### ISSUE TITLE
Polygraphy GPU memory leak when processing a large enough number of images

### ISSUE THREAD

**Issue by donrax** [NVIDIA/TensorRT#3791]
## Description

Processing a large enough number of images with Polygraphy results in GPU memory leak in method `_get_array_on_cpu`

## Environment

**TensorRT Version**: 10.0.0.6

**NVIDIA GPU**: RTX A4500

**NVIDIA Driver Version**: 551.61  

**CUDA Version**: 11.8

**CUDNN Version**: 8.9

Operating System: [22.04 LTS](https://ubuntu.com/blog/tag/22-04-lts)

Python Version (if applicable): 3.10

## Relevant Files

**File**: https://github.com/NVIDIA/TensorRT/blob/5eeb6c7b7c822d1cba0bd0d2c584c7c6b1383d64/tools/Polygraphy/polygraphy/backend/trt/runner.py#L121

## Steps To Reproduce

Simply process a large enough number of images to fill up the GPU memory.

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: The issue presist in the latest release.

## Possible solution

Deallocate `src` data pointer after copying array to cpu at line 129 with:
`cuda.wrapper().free(util.array.data_ptr(arr))`

**Comment by pranavm-nvidia** [comment]
The device buffers are owned by the output allocator and should be freed when the runner that owns it goes out of scope. Do you have a reproducer for this?

**Comment by donrax** [comment]
A code snippet that can reproduce the issue:

```python 
from polygraphy.backend.trt import TrtRunner
from polygraphy.comparator.struct import RunResults, IterationResult

runners = [TrtRunner(engine0), TrtRunner(engine1)]
for r in runners:
    r.activate()
for n, inputs in enumerate(data_loader):
    results = RunResults()
    for r, i in zip(runners, inputs):
        results.append((r.name, IterationResult(outputs=r.infer(i))))
for r in runners:
    r.deactivate()
```

**Comment by pranavm-nvidia** [comment]
Does it matter what kind of model it is? I tried your code with a simple model with large input shapes but the GPU memory usage is completely stable.

**Comment by donrax** [comment]
The model was not at fault, the memory leak occurred specifically while using Polygraphy.

However you are correct, the memory leak in Polygraphy has been fixed. Originally the tested version with the memory leak was Polygraphy 0.49.0, while version 0.49.9 is stable without memory leaks.

**Comment by donrax** [comment]
After a detailed recheck, we have noticed the following for Polygraphy version 0.49.9:

- If the TensorRT repo is cloned and Polygraphy is installed from the cloned repo, there is no memory leak
- If Polygraphy is installed from The Python Package Index (PyPI), there is no memory leak
- If Polygraphy is installed using `PIP_EXTRA_INDEX_URL='https://pypi.nvidia.com'` a memory leak occurs

What is the preferred way to install or which is the correct package index to use for TensorRT (PyPI has no version 10.0.0)?

**Comment by pranavm-nvidia** [comment]
To answer your first question, the regular PyPI is the right place. 10.0 is still in early access so `pip` won't pick up that version automatically, but you can install it by specifying the version explicitly. See https://pypi.org/project/tensorrt/10.0.0b6/

**Comment by ttyio** [comment]
closing since no activity for more than 3 weeks, pls reopen if you still have question, thanks all!

**Comment by michaeldeyzel** [comment]
For those who are still experiencing memory leaks, even with the newest version of Polygraphy, the only version that worked for me was 0.47.1 from NVIDIA's PyPi. It might solve your memory issues:
`python -m pip install "polygraphy==0.47.1" --index-url https://pypi.ngc.nvidia.com`
