### ISSUE TITLE
Cannot find "<TensorRT root directory>/samples/sample_uff_maskRCNN" dir --> UFF parser error

### ISSUE THREAD

**Issue by jqx37** [NVIDIA/TensorRT#424]
Dear all,
I managed to convert the Keras .h5 model to a UFF model. However, when I was following the instructions in https://github.com/NVIDIA/TensorRT/tree/release/7.0/samples/opensource/sampleUffMaskRCNN example post, I would not be able to find this "<TensorRT root directory>/samples/sample_uff_maskRCNN" dir. I am using a Jetson Nano device, and all the related libs/packages should have already been installed. 
Thanks in advance.

Make an update. I found the "<TensorRT root directory>/samples" dir, but there is no folder called sample_uff_maskRCNN, and after I saw this post: https://devtalk.nvidia.com/default/topic/1066605/sampleufffasterrcnn-and-sampleuffmaskrcnn-not-available-after-tensorrt-6-0-1-update/?offset=3, I think the folder is still not available. So, does anyone find a way to work around this? I am currently trying to write my own version of the program to read and use the uff file to do the inference.

**Comment by JingyuQian** [comment]
I haven't used Jetson Nano, but I touched an AGX system before. I suspect while on Jetson Nano the examples are not installed? Cause it's more of a runtime system.

As a workaround it should be OK to copy a sample folder to your Jetson Nano device and then do `make`.

**Comment by jqx37** [comment]
@JingyuQian Thanks. I think it might be, and I also may need to refresh the Jetpack if other methods failed. I found the root of tensorrt lib later yesterday. However, I could not find the sample in the dir that the tutorial specified. I am trying to implement this post: https://github.com/NVIDIA/TensorRT/issues/123. At "cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out" this line, I have an error: NO CMAKE_CUDA_COMPILER could be found. Will keep posting my progress and solution then.

**Comment by rmccorm4** [comment]
Hi,

`<TensorRT_ROOT>` is generally found at `/usr/src/tensorrt` or `/opt/tensorrt`.

As far as that devtalk post goes, if the samples don't actually come with the release and you need to build the OSS samples, try checking out this post for building on Jetson: https://github.com/NVIDIA/TensorRT/issues/9#issuecomment-575106079

That post was for a Jetson TX2, so you may need to tweak some of the variables for Jetson Nano.

**Comment by rmccorm4** [comment]
Though it looks like there may be an issue with that specific sample at the moment, just a heads up: https://github.com/NVIDIA/TensorRT/issues/418

**Comment by jqx37** [comment]
@rmccorm4 Thank you for your response. I would be able to find that root dir not. However, I could not find that sample folder. I re-installed the JetPack, and the version on the downloaded compressed file is r32.3.1. After the re-installation, I would be able to find 
libnvinfer-plugin-dev
libnvinfer-plugin6
which I could be find there two plug-ins before. So, I think I could not link the custom layers properly. I will try to compile the example again, and create the UFF file to see if I would be able to use the files. I will keep posting my results.

**Comment by jqx37** [comment]
Still have problem building TensorRT OSS. Following the instructions here: https://github.com/NVIDIA/TensorRT#download-jetpack-packages-for-cross-compilationoptional
" 
cd $TRT_SOURCE
 mkdir -p build && cd build
 cmake .. -DTRT_LIB_DIR=$TRT_RELEASE/lib -DTRT_BIN_DIR=`pwd`/out --> Error
 "
The prompt gave me error said "cmake cuda compiler not found". Will try to directly convert the h5 weights to a uff file, then try if I can use the uff file since I have the following files installed:
libnvinfer-plugin-dev
libnvinfer-plugin6

**Comment by jqx37** [comment]
Update:
I already converted the TensorFlow Model h5 model to a UFF model. The same errors still persist. Here is a screen shot of the error: 
![UFF-Parse-Error](https://user-images.githubusercontent.com/45073029/76896071-35ae0400-685f-11ea-818d-d2f056ad75e9.png)
I think this is a problem due to the unsupported custom layers. Probably the only way to make it work is to see if I would be able to use the Custom layer API to re-write those custom layers. Will keep my updates.

**Comment by zhaochenyuangit** [comment]
Hello! For the Cmake cuda compiler not found error you may try to add cuda to the environment path: 
# Add this to your .bashrc file
export CUDA_HOME=/usr/local/cuda
# Adds the CUDA compiler to the PATH
export PATH=$CUDA_HOME/bin:$PATH
# Adds the libraries
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
Reference: https://docs.donkeycar.com/guide/robot_sbc/tensorrt_jetson_nano/
As long as you can see cuda infomation by typing in the command $nvcc --version, it should solve the problem.

**Comment by zhaochenyuangit** [comment]
And since the sampleUffMaskRcnn is released in July 2019, the image for jetson nano on the Nvidia offcial website has not include the sample yet. But you can clone the actuall repo and find the maskrcnn sample under /TensorRT/samples/opensource/sampleUffMaskRcnn. Make it and the binary will be found in /TensorRT/build/out.

**Comment by jqx37** [comment]
@zhaochenyuangit Thanks for your reply. My problem was due to the CMake was not installed on my Nano correctly. I finally installed CMake on the Nano, and I generated a UFF file from the h5 weights. However, I still have problems when I try to use the UFF model to conduct inference. The fault showed me that the "PyramidROI" layer is not supported, and I think this is because the program cannot link the C++ "PyramidROI" plugin to the model. Currently, I cannot find a way to fix this on my Nano.  I am reading the documentation that introduces how to write a customized plugin in Python. If I have more information, I will post it here to share it with others. Thanks again for your help!

**Comment by zhaochenyuangit** [comment]
@jqx37 can you share the sample program file you used on nano? Currently I have converted the h5 weights to uff as well. However when I run the sampleUffMaskRCNN program enclosed in the repo, the program always eat up all 4GB memory on nano and 3 out of 6GB swap file. The program then get killed.

**Comment by JingyuQian** [comment]
@zhaochenyuangit Not sure if this is related but in sampleUffMaskRCNN.cpp there's the following:
```cpp
builder->setMaxBatchSize(mParams.batchSize);
builder->setMaxWorkspaceSize(2_GiB);
builder->setFp16Mode(mParams.fp16);
```

`maxWorkspaceSize` is the maximum amount of scratch space which the engine may
use at runtime (according to user guide). Maybe try a smaller number to see if it changes anything?

**Comment by jqx37** [comment]
@zhaochenyuangit 
Hi. I haven't gone that far yet. When I used a Python script to read the UFF file, the "PyramidROI layer not supported" error will populate, which prevents me from doing any further operations. For the memory consumption issue, I tried to add the following lines at the beginning of the "model.py" file to limit the memory consumption.
###########################
gpu_config.gpu_options.allow_growth = True
session = tf.Session(config=gpu_config)
K.set_session(session)
##############################
Though the VRAM still will be used up without any difference, I could see that the VRAM usage increased gradually compared to a sudden change when I quote those lines (which is what the code supposed to do). Even though I have those lines, the program will consume all of the 8GB VRAM in my RTX 2080 in the training process anyway. The only difference is that when I implement those lines, the VRAM will be fully consumed when the training starts. On the other hand, if those lines are quoted, the VRAM will be occupied immediately when I start the program.
Noticeably, when I have those lines, the program will consume roughly 5GB VRAM when I conduct image segmentation tasks. I am not sure if those lines will actually help me to reduce the memory consumption, but those lines may be served as a reference for you.

**Comment by JingyuQian** [comment]
@jqx37 `allow_growth=True` changes how TensorFlow uses GPU memory. By default (which is False) it takes up all available GPU memory. Setting it to True then the session will gradually expand as it requires more memory to construct the network and ops. This is consistent with what you observed. However, this is related to TensorFlow, so TensorRT might not be affected.

**Comment by jqx37** [comment]
@JingyuQian Thanks for the clarification. Interestingly, when the image resolution is 640 * 480, the batch size can be 1 or 2, and the VRAM consumption is 8GB under both circumstances. That is the reason I feel confused since when the batch size is 1, the model should not use 8GB of the VRAM, but actually it does. So I am not sure if the lines of code will do any help or not.

**Comment by JingyuQian** [comment]
@jqx37 [https://stackoverflow.com/questions/37775979/tensorflow-uses-same-amount-of-gpu-memory-regardless-of-batch-size](https://stackoverflow.com/questions/37775979/tensorflow-uses-same-amount-of-gpu-memory-regardless-of-batch-size) according to this post, it's probably related to memory fragmentation. I'm afraid I can't provide more insight in this matter.

**Comment by jqx37** [comment]
@JingyuQian Thank you for the information! That seems to be a very good explanation to me. I think that might be a reason that I can either use batch size =1 or 2 in the training process.

**Comment by rajeevsrao** [comment]
@jqx37 is your issue resolved - can this be closed?

**Comment by jqx37** [comment]
> @jqx37 is your issue resolved - can this be closed?

Hi Rajeev, Thanks for your reply. I did not have a chance to test the solution yet. However, if we can reopen it later after I test it, we can close the issue now. Please let me know if you have any questions. Thanks.

**Comment by ttyio** [comment]
> > @jqx37 is your issue resolved - can this be closed?
> 
> Hi Rajeev, Thanks for your reply. I did not have a chance to test the solution yet. However, if we can reopen it later after I test it, we can close the issue now. Please let me know if you have any questions. Thanks.

closing, please reopen if you still have question, thanks!
